export interface ProjectComposeConfig {
  projectSlug: string;
  dbName: string;
  dbUser: string;
  dbPassword: string;
  jwtSecret: string;
  anonKey: string;
  serviceRoleKey: string;
  apiExternalUrl: string;
  siteUrl: string;
  hostPortBase: number;
  // Resource limits — used for Postgres tuning
  ramMbLimit: number;
  vcpuLimit: number;
  // Optional SMTP relay
  smtpHost?: string;
  smtpPort?: number;
  smtpUser?: string;
  smtpPass?: string;
  // WAL archiving
  walArchiveEnabled?: boolean;
}

// Calculate sensible Postgres parameters from the project's RAM allocation
function pgTuning(ramMb: number) {
  const sharedBuffersMb  = Math.floor(ramMb * 0.25);
  const effectiveCacheMb = Math.floor(ramMb * 0.75);
  const workMemMb        = Math.max(4, Math.floor(ramMb / 100));
  return { sharedBuffersMb, effectiveCacheMb, workMemMb };
}

export function generatePostgresqlConf(ramMb: number, walArchiveEnabled = false): string {
  const { sharedBuffersMb, effectiveCacheMb, workMemMb } = pgTuning(ramMb);
  const walLines = walArchiveEnabled
    ? `
wal_level = replica
archive_mode = on
archive_command = 'cp %p /var/lib/postgresql/wal-archive/%f'
archive_timeout = 60`
    : "";

  return `
# Auto-tuned by GuildServer BaaS scheduler
shared_buffers            = ${sharedBuffersMb}MB
effective_cache_size      = ${effectiveCacheMb}MB
work_mem                  = ${workMemMb}MB
maintenance_work_mem      = ${Math.floor(ramMb * 0.05)}MB
max_connections           = 100
checkpoint_completion_target = 0.9
wal_buffers               = 16MB
default_statistics_target = 100
random_page_cost          = 1.1
effective_io_concurrency  = 200
max_worker_processes      = 4
max_parallel_workers_per_gather = 2
max_parallel_workers      = 4
${walLines}
`.trimStart();
}

export function generateKongConfig(cfg: { anonKey: string; serviceRoleKey: string }): string {
  return `
_format_version: "2.1"
_transform: true

consumers:
  - username: anon
    keyauth_credentials:
      - key: ${cfg.anonKey}
  - username: service_role
    keyauth_credentials:
      - key: ${cfg.serviceRoleKey}

acls:
  - consumer: anon
    group: anon
  - consumer: service_role
    group: admin

services:
  - name: auth-v1-open
    url: http://auth:9999/verify
    routes:
      - name: auth-v1-open
        strip_path: true
        paths:
          - /auth/v1/verify
    plugins:
      - name: cors
  - name: auth-v1
    url: http://auth:9999
    routes:
      - name: auth-v1
        strip_path: true
        paths:
          - /auth/v1/
    plugins:
      - name: cors
      - name: key-auth
        config:
          hide_credentials: false
      - name: acl
        config:
          hide_groups_header: true
          allow: [anon, admin]
  - name: rest-v1
    url: http://rest:3000
    routes:
      - name: rest-v1
        strip_path: true
        paths:
          - /rest/v1/
    plugins:
      - name: cors
      - name: key-auth
        config:
          hide_credentials: true
      - name: acl
        config:
          hide_groups_header: true
          allow: [anon, admin]
  - name: realtime-v1
    url: http://realtime:4000/socket
    routes:
      - name: realtime-v1
        strip_path: true
        paths:
          - /realtime/v1/
    plugins:
      - name: cors
      - name: key-auth
        config:
          hide_credentials: false
      - name: acl
        config:
          hide_groups_header: true
          allow: [anon, admin]
  - name: storage-v1
    url: http://storage:5000
    routes:
      - name: storage-v1
        strip_path: true
        paths:
          - /storage/v1/
    plugins:
      - name: cors
      - name: key-auth
        config:
          hide_credentials: true
      - name: acl
        config:
          hide_groups_header: true
          allow: [anon, admin]
  - name: meta
    url: http://meta:8080
    routes:
      - name: meta
        strip_path: true
        paths:
          - /pg/
    plugins:
      - name: key-auth
        config:
          hide_credentials: true
      - name: acl
        config:
          hide_groups_header: true
          allow: [admin]
  - name: functions-v1
    url: http://functions:9000
    routes:
      - name: functions-v1
        strip_path: true
        paths:
          - /functions/v1/
    plugins:
      - name: cors
      - name: key-auth
        config:
          hide_credentials: true
      - name: acl
        config:
          hide_groups_header: true
          allow: [anon, admin]
`.trimStart();
}

export function generateComposeYml(cfg: ProjectComposeConfig): string {
  const s = cfg.projectSlug;
  const base = cfg.hostPortBase;
  const smtp = {
    host: cfg.smtpHost ?? "localhost",
    port: cfg.smtpPort ?? 25,
    user: cfg.smtpUser ?? "",
    pass: cfg.smtpPass ?? "",
  };
  const { vcpuLimit: cpu, ramMbLimit: ram } = cfg;
  const walMount = cfg.walArchiveEnabled
    ? `      - ./volumes/wal-archive:/var/lib/postgresql/wal-archive` : "";

  return `# Auto-generated by GuildServer BaaS scheduler — do not edit manually
# Project: ${s}
name: baas-${s}

x-restart: &restart
  restart: unless-stopped

services:

  # ── Database ────────────────────────────────────────────────────────────────
  db:
    <<: *restart
    image: supabase/postgres:17.6.1.136
    container_name: baas-${s}-db
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_HOST: /var/run/postgresql
      PGPORT: 5432
      POSTGRES_PORT: 5432
      PGPASSWORD: ${cfg.dbPassword}
      POSTGRES_PASSWORD: ${cfg.dbPassword}
      PGDATABASE: postgres
      POSTGRES_DB: postgres
      JWT_SECRET: ${cfg.jwtSecret}
      JWT_EXP: 3600
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
      - ./volumes/db/postgresql.conf:/etc/postgresql/postgresql.conf
${walMount}
    deploy:
      resources:
        limits:
          cpus: '${(cpu * 0.25).toFixed(2)}'
          memory: ${Math.floor(ram * 0.4)}m

  # ── Connection pooler ───────────────────────────────────────────────────────
  supavisor:
    <<: *restart
    image: supabase/supavisor:2.9.5
    container_name: baas-${s}-supavisor
    ports:
      - "${base + 3}:5432"
    environment:
      CLUSTER_POSTGRES: "true"
      SECRET_KEY_BASE: ${cfg.jwtSecret}
      VAULT_ENC_KEY: ${cfg.jwtSecret.slice(0, 32)}
      API_JWT_SECRET: ${cfg.jwtSecret}
      METRICS_JWT_SECRET: ${cfg.jwtSecret}
      REGION: local
      LOGS_LEVEL: info
      POOLER_DEFAULT_POOL_SIZE: 20
      POOLER_MAX_CLIENT_CONN: 200
      DATABASE_URL: ecto://postgres:${cfg.dbPassword}@db:5432/postgres
    depends_on:
      db: { condition: service_healthy }

  # ── API Gateway ─────────────────────────────────────────────────────────────
  kong:
    <<: *restart
    image: kong:3.9.1
    container_name: baas-${s}-kong
    ports:
      - "${base + 0}:8000"
      - "${base + 1}:8443"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
    volumes:
      - ./volumes/api/kong.yml:/var/lib/kong/kong.yml:ro
    depends_on:
      db: { condition: service_healthy }

  # ── Auth (GoTrue) ──────────────────────────────────────────────────────────
  auth:
    <<: *restart
    image: supabase/gotrue:v2.189.0
    container_name: baas-${s}-auth
    environment:
      GOTRUE_API_HOST: "0.0.0.0"
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: ${cfg.apiExternalUrl}
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://supabase_auth_admin:${cfg.dbPassword}@db:5432/postgres
      GOTRUE_SITE_URL: ${cfg.siteUrl}
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: 3600
      GOTRUE_JWT_SECRET: ${cfg.jwtSecret}
      GOTRUE_SMTP_HOST: ${smtp.host}
      GOTRUE_SMTP_PORT: ${smtp.port}
      GOTRUE_SMTP_USER: ${smtp.user}
      GOTRUE_SMTP_PASS: ${smtp.pass}
      GOTRUE_MAILER_AUTOCONFIRM: "true"
    depends_on:
      db: { condition: service_healthy }

  # ── REST API (PostgREST) ───────────────────────────────────────────────────
  rest:
    <<: *restart
    image: postgrest/postgrest:v14.12
    container_name: baas-${s}-rest
    environment:
      PGRST_DB_URI: postgres://authenticator:${cfg.dbPassword}@db:5432/postgres
      PGRST_DB_SCHEMAS: public,storage,graphql_public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${cfg.jwtSecret}
      PGRST_DB_USE_LEGACY_GUCS: "false"
      PGRST_APP_SETTINGS_JWT_SECRET: ${cfg.jwtSecret}
      PGRST_APP_SETTINGS_JWT_EXP: 3600
    depends_on:
      db: { condition: service_healthy }

  # ── Realtime ────────────────────────────────────────────────────────────────
  realtime:
    <<: *restart
    image: supabase/realtime:v2.102.3
    container_name: baas-${s}-realtime
    environment:
      PORT: 4000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: supabase_admin
      DB_PASSWORD: ${cfg.dbPassword}
      DB_NAME: postgres
      DB_AFTER_CONNECT_QUERY: "SET search_path TO _realtime"
      DB_ENC_KEY: ${cfg.jwtSecret.slice(0, 16)}
      API_JWT_SECRET: ${cfg.jwtSecret}
      FLY_ALLOC_ID: localdev
      FLY_APP_NAME: baas-${s}-realtime
      SECRET_KEY_BASE: ${cfg.jwtSecret}
      ERL_AFLAGS: -proto_dist inet_tcp
      DNS_NODES: "''"
      RLIMIT_NOFILE: "10000"
    depends_on:
      db: { condition: service_healthy }

  # ── Storage API ─────────────────────────────────────────────────────────────
  storage:
    <<: *restart
    image: supabase/storage-api:v1.60.4
    container_name: baas-${s}-storage
    environment:
      ANON_KEY: ${cfg.anonKey}
      SERVICE_KEY: ${cfg.serviceRoleKey}
      POSTGREST_URL: http://rest:3000
      PGRST_JWT_SECRET: ${cfg.jwtSecret}
      DATABASE_URL: postgres://supabase_storage_admin:${cfg.dbPassword}@db:5432/postgres
      FILE_SIZE_LIMIT: 52428800
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      TENANT_ID: stub
      REGION: local
      GLOBAL_S3_BUCKET: stub
      ENABLE_IMAGE_TRANSFORMATION: "true"
      IMGPROXY_URL: http://imgproxy:8080
    volumes:
      - ./volumes/storage:/var/lib/storage:z
    depends_on:
      db:   { condition: service_healthy }
      rest: { condition: service_started }

  # ── Image proxy ─────────────────────────────────────────────────────────────
  imgproxy:
    <<: *restart
    image: darthsim/imgproxy:v3.30.1
    container_name: baas-${s}-imgproxy
    environment:
      IMGPROXY_BIND: ":8080"
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /
      IMGPROXY_USE_ETAG: "true"
      IMGPROXY_ENABLE_WEBP_DETECTION: "true"
    volumes:
      - ./volumes/storage:/var/lib/storage:z

  # ── Postgres Meta ───────────────────────────────────────────────────────────
  meta:
    <<: *restart
    image: supabase/postgres-meta:v0.96.6
    container_name: baas-${s}-meta
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: db
      PG_META_DB_PORT: 5432
      PG_META_DB_NAME: postgres
      PG_META_DB_USER: supabase_admin
      PG_META_DB_PASSWORD: ${cfg.dbPassword}
    depends_on:
      db: { condition: service_healthy }

  # ── Edge Functions (Deno runtime) ────────────────────────────────────────────
  functions:
    <<: *restart
    image: supabase/edge-runtime:v1.74.0
    container_name: baas-${s}-functions
    environment:
      SUPABASE_URL: http://kong:8000
      SUPABASE_ANON_KEY: ${cfg.anonKey}
      SUPABASE_SERVICE_ROLE_KEY: ${cfg.serviceRoleKey}
      SUPABASE_DB_URL: postgresql://postgres:${cfg.dbPassword}@db:5432/postgres
      JWT_SECRET: ${cfg.jwtSecret}
      VERIFY_JWT: "false"
    volumes:
      - ./volumes/functions:/home/deno/functions:Z
    depends_on:
      db: { condition: service_healthy }

  # ── Studio ──────────────────────────────────────────────────────────────────
  studio:
    <<: *restart
    image: supabase/studio:2026.06.03-sha-0bca601
    container_name: baas-${s}-studio
    ports:
      - "${base + 2}:3000"
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: ${cfg.dbPassword}
      DEFAULT_ORGANIZATION_NAME: "${cfg.projectSlug}"
      DEFAULT_PROJECT_NAME: "${cfg.projectSlug}"
      SUPABASE_URL: http://kong:8000
      SUPABASE_PUBLIC_URL: ${cfg.apiExternalUrl}
      SUPABASE_ANON_KEY: ${cfg.anonKey}
      SUPABASE_SERVICE_KEY: ${cfg.serviceRoleKey}
      AUTH_JWT_SECRET: ${cfg.jwtSecret}
      LOGFLARE_API_KEY: unused
      LOGFLARE_URL: http://analytics:4000
      NEXT_PUBLIC_ENABLE_LOGS: "false"
    depends_on:
      - kong
      - auth
      - rest
      - storage

networks:
  default:
    name: baas-${s}
`;
}
