import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { createTRPCRouter, protectedProcedure } from "../trpc/trpc";
import {
  applications,
  members,
  domains,
  certificates,
} from "@guildserver/database";
import { eq, and } from "drizzle-orm";
import crypto from "crypto";
import * as dnsPromises from "dns/promises";
import { isLocalhostDomain } from "../services/docker";
import { verifyRedirect, verifyDns } from "../services/domain-verifier";
import { buildForwardingInstructions, buildDnsInstructions } from "../services/domain-instructions";
import {
  isCloudflareSaasConfigured,
  createCustomHostname,
  getCustomHostnameStatus,
  deleteCustomHostname,
  listCustomHostnames,
  isHostnameActive,
  getVerificationInfo,
} from "../services/cloudflare-saas";
import { syncTraefikDynamicDomains } from "../services/traefik-dynamic";

const BASE_DOMAIN = process.env.BASE_DOMAIN || "guildserver.localhost";

/** Canonical app host used as the CNAME target for vanity domains. */
function canonicalHost(app: any): string {
  const appSlug = app.appName.toLowerCase().replace(/[^a-z0-9-]/g, "-");
  return `${appSlug}.${BASE_DOMAIN}`;
}

/** Resolve our server's public IP(s) from BASE_DOMAIN for A-record verification. */
async function getServerIps(): Promise<string[]> {
  try {
    return await dnsPromises.resolve4(BASE_DOMAIN);
  } catch {
    return [];
  }
}

// Helper to check app access
async function checkAppAccess(ctx: any, applicationId: string) {
  const app = await ctx.db.query.applications.findFirst({
    where: eq(applications.id, applicationId),
    with: {
      project: {
        with: {
          organization: {
            with: {
              members: {
                where: eq(members.userId, ctx.user.id),
              },
            },
          },
        },
      },
    },
  });

  if (!app || app.project.organization.members.length === 0) {
    throw new TRPCError({
      code: "FORBIDDEN",
      message: "Application not found or access denied",
    });
  }

  return app;
}

// Generate a verification token
function generateVerificationToken(): string {
  return `gs-verify-${crypto.randomBytes(16).toString("hex")}`;
}

async function ensureAutoDomainExists(ctx: any, applicationId: string, app: any, branch?: string) {
  const appSlug = app.appName.toLowerCase().replace(/[^a-z0-9-]/g, "-");
  const autoUrl = branch
    ? `${branch}-${appSlug}.${BASE_DOMAIN}`
    : `${appSlug}.${BASE_DOMAIN}`;

  const existing = await ctx.db.query.domains.findFirst({
    where: and(
      eq(domains.applicationId, applicationId),
      eq(domains.domain, autoUrl),
      eq(domains.isAutoGenerated, true)
    ),
  });

  if (existing) {
    return existing.domain;
  }

  const hasPrimary = await ctx.db.query.domains.findFirst({
    where: and(
      eq(domains.applicationId, applicationId),
      eq(domains.isPrimary, true)
    ),
  });

  const [domain] = await ctx.db
    .insert(domains)
    .values({
      domain: autoUrl,
      applicationId: applicationId,
      isPrimary: !hasPrimary,
      isAutoGenerated: true,
      verified: true,
      status: "active",
      forceHttps: false,
    })
    .returning();

  return domain.domain;
}

export const domainRouter = createTRPCRouter({
  // List all domains for an application
  list: protectedProcedure
    .input(z.object({ applicationId: z.string().uuid() }))
    .query(async ({ ctx, input }) => {
      await checkAppAccess(ctx, input.applicationId);

      const appDomains = await ctx.db.query.domains.findMany({
        where: eq(domains.applicationId, input.applicationId),
      });

      return appDomains;
    }),

  // Add a custom domain
  add: protectedProcedure
    .input(
      z.object({
        applicationId: z.string().uuid(),
      domain: z
          .string()
          .min(3)
          .max(255)
          .regex(
            /^(\*\.)?([a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$/,
            "Invalid domain format"
          ),
        isPrimary: z.boolean().default(false),
        // "dns" → CNAME/A record (vanity domain, keeps the domain in the bar with its own SSL)
        // "redirect" → registrar URL forwarding to the canonical GuildServer URL
        method: z.enum(["dns", "redirect"]).default("dns"),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const app = await checkAppAccess(ctx, input.applicationId);

      const normalizedDomain = input.domain.trim().toLowerCase();
      const canonicalDomain = await ensureAutoDomainExists(ctx, input.applicationId, app);

      // Check if domain is already registered
      const existing = await ctx.db.query.domains.findFirst({
        where: eq(domains.domain, normalizedDomain),
      });

      if (existing) {
        throw new TRPCError({
          code: "CONFLICT",
          message: `Domain ${normalizedDomain} is already registered`,
        });
      }

      // If setting as primary, unset other primary domains
      if (input.isPrimary) {
        await ctx.db
          .update(domains)
          .set({ isPrimary: false })
          .where(eq(domains.applicationId, input.applicationId));
      }

      if (input.method === "dns") {
        // If Cloudflare for SaaS is configured, register the custom hostname
        // so Cloudflare will accept traffic for this external domain and route
        // it through our tunnel.
        let cfHostnameId: string | null = null;
        let cfHostnameStatus: string | null = null;
        let cfOwnershipVerification: { name: string; value: string } | undefined;
        let cfSslValidationRecords: any[] | undefined;

        if (isCloudflareSaasConfigured()) {
          try {
            const cfResult = await createCustomHostname({
              hostname: normalizedDomain,
              sslMethod: "http",
            });
            cfHostnameId = cfResult.id;
            cfHostnameStatus = cfResult.status;
            cfOwnershipVerification = cfResult.ownershipVerification;
            cfSslValidationRecords = cfResult.sslValidationRecords;
          } catch (error: any) {
            // If the hostname already exists on Cloudflare, fetch and adopt it
            if (error?.message?.includes("already exists")) {
              try {
                const { hostnames } = await listCustomHostnames({ hostname: normalizedDomain });
                const existingCf = hostnames.find(
                  (h) => h.hostname.toLowerCase() === normalizedDomain
                );
                if (existingCf) {
                  cfHostnameId = existingCf.id;
                  cfHostnameStatus = existingCf.status;
                  const info = getVerificationInfo(existingCf);
                  if (info.txtRecords.length > 0) {
                    cfOwnershipVerification = info.txtRecords[0];
                  }
                  cfSslValidationRecords = existingCf.ssl?.validation_records;
                }
              } catch (listErr: any) {
                console.warn(`Could not fetch existing Cloudflare hostname: ${listErr.message}`);
              }
            } else {
              console.error(`Cloudflare custom hostname creation failed: ${error.message}`);
            }
          }
        }

        const [domain] = await ctx.db
          .insert(domains)
          .values({
            domain: normalizedDomain,
            applicationId: input.applicationId,
            isPrimary: input.isPrimary,
            isAutoGenerated: false,
            verificationMethod: "dns",
            verified: false,
            status: "pending",
            forceHttps: true,
            redirectsTo: null,
            cfCustomHostnameId: cfHostnameId,
            cfCustomHostnameStatus: cfHostnameStatus,
          })
          .returning();

        const serverIps = await getServerIps();
        return {
          ...domain,
          dnsInstructions: buildDnsInstructions({
            domain: normalizedDomain,
            cnameTarget: canonicalHost(app),
            apexIp: serverIps[0] ?? null,
          }),
          // Surface Cloudflare verification info so the UI can show it
          cfOwnershipVerification,
          cfSslValidationRecords,
        };
      }

      const [domain] = await ctx.db
        .insert(domains)
        .values({
          domain: normalizedDomain,
          applicationId: input.applicationId,
          isPrimary: input.isPrimary,
          isAutoGenerated: false,
          verificationMethod: "redirect",
          verified: false,
          status: "pending",
          forceHttps: true,
          redirectsTo: canonicalDomain,
        })
        .returning();

      return {
        ...domain,
        forwardingInstructions: buildForwardingInstructions({
          domain: normalizedDomain,
          target: canonicalDomain
        }),
      };
    }),

  // Generate auto-assigned domain for an application
  generateAutoUrl: protectedProcedure
    .input(
      z.object({
        applicationId: z.string().uuid(),
        branch: z.string().optional(),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const app = await checkAppAccess(ctx, input.applicationId);
      const url = await ensureAutoDomainExists(ctx, input.applicationId, app, input.branch);
      
      const domain = await ctx.db.query.domains.findFirst({
        where: and(
          eq(domains.applicationId, input.applicationId),
          eq(domains.domain, url),
          eq(domains.isAutoGenerated, true)
        )
      });
      
      if (!domain) {
        throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Failed to generate auto URL" });
      }
      
      return domain;
    }),

  // Verify domain ownership via DNS
  verify: protectedProcedure
    .input(z.object({ id: z.string().uuid(), applicationId: z.string().uuid() }))
    .mutation(async ({ ctx, input }) => {
      const app = await checkAppAccess(ctx, input.applicationId);

      const domain = await ctx.db.query.domains.findFirst({
        where: and(
          eq(domains.id, input.id),
          eq(domains.applicationId, input.applicationId)
        ),
      });

      if (!domain) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Domain not found",
        });
      }

      // DNS / vanity domains: confirm the CNAME/A record points at our servers.
      if (domain.verificationMethod === "dns" || domain.verificationMethod === "cname") {
        // Step 1: Check if DNS resolves to our servers
        const serverIps = await getServerIps();
        const dnsResult = await verifyDns({
          domain: domain.domain,
          cnameTarget: canonicalHost(app),
          serverIps,
        });

        // Step 2: If Cloudflare for SaaS is configured and we have a hostname ID,
        // also check the custom hostname status on Cloudflare's side.
        let cfStatus: string | null = null;
        let cfVerificationInfo: ReturnType<typeof getVerificationInfo> | null = null;

        if (isCloudflareSaasConfigured() && domain.cfCustomHostnameId) {
          try {
            const cfHostname = await getCustomHostnameStatus(domain.cfCustomHostnameId);
            if (cfHostname) {
              cfStatus = cfHostname.status;
              cfVerificationInfo = getVerificationInfo(cfHostname);
            }
          } catch {
            // Non-fatal — DNS verification alone is still useful
          }
        }

        // Domain is fully verified when DNS resolves AND (CF is not configured
        // OR CF reports the hostname as active).
        const dnsOk = dnsResult.status === "active";
        const cfOk = !isCloudflareSaasConfigured() || !domain.cfCustomHostnameId || cfStatus === "active";
        const isVerified = dnsOk && cfOk;

        let verificationError = dnsResult.reason || null;
        if (dnsOk && !cfOk && cfStatus) {
          verificationError = `DNS is correct but Cloudflare SSL is still ${cfStatus}. This usually resolves automatically within a few minutes.`;
        }

        const [updated] = await ctx.db
          .update(domains)
          .set({
            verified: isVerified,
            status: isVerified ? "active" : "failed",
            lastCheckedAt: new Date(),
            verificationError,
            cfCustomHostnameStatus: cfStatus,
            updatedAt: new Date(),
          })
          .where(eq(domains.id, input.id))
          .returning();

        if (updated.verified) {
          void syncTraefikDynamicDomains();
        }

        return {
          verified: updated.verified,
          domain: updated,
          // Traefik dynamically routes the domain immediately without a redeploy.
          needsRedeploy: false,
          cfVerificationInfo,
        };
      }

      if (domain.verified && domain.verificationMethod !== "redirect") {
        return { verified: true, domain };
      }

      if (domain.verificationMethod === "redirect" && domain.redirectsTo) {
        const checkSampleDomain = domain.domain.startsWith("*.") ? `gscheck.${domain.domain.slice(2)}` : domain.domain;
        const result = await verifyRedirect({ domain: checkSampleDomain, expectedTarget: domain.redirectsTo });

        const [updated] = await ctx.db
          .update(domains)
          .set({
            verified: result.status === "active",
            status: result.status,
            lastCheckedAt: new Date(),
            verificationError: result.reason || null,
            lastHttpStatus: result.httpStatus || null,
            updatedAt: new Date(),
          })
          .where(eq(domains.id, input.id))
          .returning();

        return { verified: updated.verified, domain: updated };
      }

      // Legacy fallback
      const [updated] = await ctx.db
        .update(domains)
        .set({
          verified: true,
          status: "active",
          updatedAt: new Date(),
        })
        .where(eq(domains.id, input.id))
        .returning();

      return { verified: true, domain: updated };
    }),

  // Set a domain as primary
  setPrimary: protectedProcedure
    .input(z.object({ id: z.string().uuid(), applicationId: z.string().uuid() }))
    .mutation(async ({ ctx, input }) => {
      await checkAppAccess(ctx, input.applicationId);

      // Unset all other primary domains for this app
      await ctx.db
        .update(domains)
        .set({ isPrimary: false })
        .where(eq(domains.applicationId, input.applicationId));

      // Set selected domain as primary
      const [updated] = await ctx.db
        .update(domains)
        .set({ isPrimary: true, updatedAt: new Date() })
        .where(
          and(
            eq(domains.id, input.id),
            eq(domains.applicationId, input.applicationId)
          )
        )
        .returning();

      if (!updated) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Domain not found",
        });
      }

      return updated;
    }),

  // Remove a domain
  remove: protectedProcedure
    .input(z.object({ id: z.string().uuid(), applicationId: z.string().uuid() }))
    .mutation(async ({ ctx, input }) => {
      await checkAppAccess(ctx, input.applicationId);

      const domain = await ctx.db.query.domains.findFirst({
        where: and(
          eq(domains.id, input.id),
          eq(domains.applicationId, input.applicationId)
        ),
      });

      if (!domain) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Domain not found",
        });
      }

      // Clean up the Cloudflare custom hostname if one was created
      if (domain.cfCustomHostnameId && isCloudflareSaasConfigured()) {
        try {
          await deleteCustomHostname(domain.cfCustomHostnameId);
        } catch (error: any) {
          // Log but don't block deletion — the CF hostname may have been
          // removed manually from the dashboard.
          console.error(`Failed to delete CF custom hostname ${domain.cfCustomHostnameId}: ${error.message}`);
        }
      }

      await ctx.db.delete(domains).where(eq(domains.id, input.id));
      void syncTraefikDynamicDomains();

      return { success: true };
    }),

  // Get certificate/SSL status for domains
  getCertificateStatus: protectedProcedure
    .input(z.object({ applicationId: z.string().uuid() }))
    .query(async ({ ctx, input }) => {
      await checkAppAccess(ctx, input.applicationId);

      const appDomains = await ctx.db.query.domains.findMany({
        where: eq(domains.applicationId, input.applicationId),
      });

      return appDomains.map((domain) => {
        const isLocal = isLocalhostDomain(domain.domain);

        if (isLocal) {
          return {
            domainId: domain.id,
            domain: domain.domain,
            sslStatus: "not_applicable" as const,
            sslMessage: "SSL is not required for localhost/local domains",
            isLocal: true,
          };
        }

        // For redirect aliases, TLS is handled at the registrar level
        if (domain.verificationMethod === "redirect") {
          return {
            domainId: domain.id,
            domain: domain.domain,
            sslStatus: "not_applicable" as const,
            sslMessage: "TLS is handled by your registrar's forwarding; the app itself is served over HTTPS at its guild-technologies.com URL.",
            isLocal: false,
          };
        }

        // For real domains, Traefik handles certificate provisioning via ACME
        // Certificate status is determined by whether the domain is active + verified
        if (!domain.verified) {
          return {
            domainId: domain.id,
            domain: domain.domain,
            sslStatus: "pending_verification" as const,
            sslMessage: "Domain must be verified before SSL can be provisioned",
            isLocal: false,
          };
        }

        // Cloudflare for SaaS custom domains: SSL is managed by Cloudflare
        if (domain.cfCustomHostnameId) {
          const cfSslActive = domain.cfCustomHostnameStatus === "active";
          return {
            domainId: domain.id,
            domain: domain.domain,
            sslStatus: cfSslActive ? ("active" as const) : ("provisioning" as const),
            sslMessage: cfSslActive
              ? "SSL certificate auto-managed by Cloudflare for SaaS"
              : `Cloudflare SSL provisioning in progress (status: ${domain.cfCustomHostnameStatus || "pending"})`,
            isLocal: false,
          };
        }

        return {
          domainId: domain.id,
          domain: domain.domain,
          sslStatus: "active" as const,
          sslMessage: "SSL certificate auto-managed by Let's Encrypt via Traefik",
          isLocal: false,
        };
      });
    }),

  // Get the access URL for an application (primary domain or localhost:port)
  getAccessUrl: protectedProcedure
    .input(z.object({ applicationId: z.string().uuid() }))
    .query(async ({ ctx, input }) => {
      await checkAppAccess(ctx, input.applicationId);

      // First check for a primary domain
      const primaryDomain = await ctx.db.query.domains.findFirst({
        where: and(
          eq(domains.applicationId, input.applicationId),
          eq(domains.isPrimary, true),
          eq(domains.status, "active")
        ),
      });

      if (primaryDomain) {
        const protocol = primaryDomain.forceHttps ? "https" : "http";
        return {
          url: `${protocol}://${primaryDomain.domain}`,
          type: "domain" as const,
          domain: primaryDomain.domain,
        };
      }

      // Check for any active domain
      const anyDomain = await ctx.db.query.domains.findFirst({
        where: and(
          eq(domains.applicationId, input.applicationId),
          eq(domains.status, "active")
        ),
      });

      if (anyDomain) {
        const protocol = anyDomain.forceHttps ? "https" : "http";
        return {
          url: `${protocol}://${anyDomain.domain}`,
          type: "domain" as const,
          domain: anyDomain.domain,
        };
      }

      // Fallback: no domain, try to get port from container
      return {
        url: null,
        type: "none" as const,
        domain: null,
      };
    }),

  getInstructions: protectedProcedure
    .input(z.object({ id: z.string().uuid(), applicationId: z.string().uuid() }))
    .query(async ({ ctx, input }) => {
      const app = await checkAppAccess(ctx, input.applicationId);

      const domain = await ctx.db.query.domains.findFirst({
        where: and(
          eq(domains.id, input.id),
          eq(domains.applicationId, input.applicationId)
        ),
      });

      if (!domain) {
        throw new TRPCError({ code: "NOT_FOUND", message: "Domain not found" });
      }

      // Redirect (URL forwarding) domains.
      if (domain.verificationMethod === "redirect") {
        if (!domain.redirectsTo) {
          throw new TRPCError({ code: "BAD_REQUEST", message: "Domain is missing its forwarding target" });
        }
        return buildForwardingInstructions({
          domain: domain.domain,
          target: domain.redirectsTo,
        });
      }

      // DNS / vanity domains (default).
      const serverIps = await getServerIps();
      return buildDnsInstructions({
        domain: domain.domain,
        cnameTarget: canonicalHost(app),
        apexIp: serverIps[0] ?? null,
      });
    }),
});
