import { z } from "zod";
import { TRPCError } from "@trpc/server";
import { createTRPCRouter, protectedProcedure } from "../trpc/trpc";
import {
  applications,
  members,
  domains,
  certificates,
} from "@guildserver/database";
import { eq, and } from "drizzle-orm";
import crypto from "crypto";
import { isLocalhostDomain } from "../services/docker";

const BASE_DOMAIN = process.env.BASE_DOMAIN || "guildserver.localhost";

// Helper to check app access
async function checkAppAccess(ctx: any, applicationId: string) {
  const app = await ctx.db.query.applications.findFirst({
    where: eq(applications.id, applicationId),
    with: {
      project: {
        with: {
          organization: {
            with: {
              members: {
                where: eq(members.userId, ctx.user.id),
              },
            },
          },
        },
      },
    },
  });

  if (!app || app.project.organization.members.length === 0) {
    throw new TRPCError({
      code: "FORBIDDEN",
      message: "Application not found or access denied",
    });
  }

  return app;
}

// Generate a verification token
function generateVerificationToken(): string {
  return `gs-verify-${crypto.randomBytes(16).toString("hex")}`;
}

export const domainRouter = createTRPCRouter({
  // List all domains for an application
  list: protectedProcedure
    .input(z.object({ applicationId: z.string().uuid() }))
    .query(async ({ ctx, input }) => {
      await checkAppAccess(ctx, input.applicationId);

      const appDomains = await ctx.db.query.domains.findMany({
        where: eq(domains.applicationId, input.applicationId),
      });

      return appDomains;
    }),

  // Add a custom domain
  add: protectedProcedure
    .input(
      z.object({
        applicationId: z.string().uuid(),
        domain: z
          .string()
          .min(3)
          .max(255)
          .regex(
            /^([a-zA-Z0-9]([a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$/,
            "Invalid domain format"
          ),
        isPrimary: z.boolean().default(false),
      })
    )
    .mutation(async ({ ctx, input }) => {
      await checkAppAccess(ctx, input.applicationId);

      // Check if domain is already registered
      const existing = await ctx.db.query.domains.findFirst({
        where: eq(domains.domain, input.domain),
      });

      if (existing) {
        throw new TRPCError({
          code: "CONFLICT",
          message: `Domain ${input.domain} is already registered`,
        });
      }

      // If setting as primary, unset other primary domains
      if (input.isPrimary) {
        await ctx.db
          .update(domains)
          .set({ isPrimary: false })
          .where(eq(domains.applicationId, input.applicationId));
      }

      const verificationToken = generateVerificationToken();

      const [domain] = await ctx.db
        .insert(domains)
        .values({
          domain: input.domain,
          applicationId: input.applicationId,
          isPrimary: input.isPrimary,
          isAutoGenerated: false,
          verificationToken,
          verificationMethod: "cname",
          verified: false,
          status: "pending",
          forceHttps: true,
        })
        .returning();

      return {
        ...domain,
        dnsInstructions: {
          type: "CNAME",
          name: `_gs-verify.${input.domain}`,
          value: verificationToken,
          description: `Add a CNAME record for _gs-verify.${input.domain} pointing to ${verificationToken}`,
          alternative: {
            type: "TXT",
            name: input.domain,
            value: verificationToken,
            description: `Or add a TXT record for ${input.domain} with value ${verificationToken}`,
          },
        },
      };
    }),

  // Generate auto-assigned domain for an application
  generateAutoUrl: protectedProcedure
    .input(
      z.object({
        applicationId: z.string().uuid(),
        branch: z.string().optional(),
      })
    )
    .mutation(async ({ ctx, input }) => {
      const app = await checkAppAccess(ctx, input.applicationId);

      // Generate URL: {app-name}.guildserver.local or {branch}-{app-name}.guildserver.local
      const appSlug = app.appName.toLowerCase().replace(/[^a-z0-9-]/g, "-");
      const autoUrl = input.branch
        ? `${input.branch}-${appSlug}.${BASE_DOMAIN}`
        : `${appSlug}.${BASE_DOMAIN}`;

      // Check if auto domain already exists
      const existing = await ctx.db.query.domains.findFirst({
        where: and(
          eq(domains.applicationId, input.applicationId),
          eq(domains.domain, autoUrl),
          eq(domains.isAutoGenerated, true)
        ),
      });

      if (existing) {
        return existing;
      }

      // If no primary domain exists, make this one primary
      const hasPrimary = await ctx.db.query.domains.findFirst({
        where: and(
          eq(domains.applicationId, input.applicationId),
          eq(domains.isPrimary, true)
        ),
      });

      const [domain] = await ctx.db
        .insert(domains)
        .values({
          domain: autoUrl,
          applicationId: input.applicationId,
          isPrimary: !hasPrimary,
          isAutoGenerated: true,
          verified: true, // Auto-generated domains are auto-verified
          status: "active",
          forceHttps: false, // Local domains don't need HTTPS
        })
        .returning();

      return domain;
    }),

  // Verify domain ownership via DNS
  verify: protectedProcedure
    .input(z.object({ id: z.string().uuid(), applicationId: z.string().uuid() }))
    .mutation(async ({ ctx, input }) => {
      await checkAppAccess(ctx, input.applicationId);

      const domain = await ctx.db.query.domains.findFirst({
        where: and(
          eq(domains.id, input.id),
          eq(domains.applicationId, input.applicationId)
        ),
      });

      if (!domain) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Domain not found",
        });
      }

      if (domain.verified) {
        return { verified: true, domain };
      }

      // In production, we'd do actual DNS lookup here
      // For now, mark as verified (simulating successful DNS check)
      const [updated] = await ctx.db
        .update(domains)
        .set({
          verified: true,
          status: "active",
          updatedAt: new Date(),
        })
        .where(eq(domains.id, input.id))
        .returning();

      return { verified: true, domain: updated };
    }),

  // Set a domain as primary
  setPrimary: protectedProcedure
    .input(z.object({ id: z.string().uuid(), applicationId: z.string().uuid() }))
    .mutation(async ({ ctx, input }) => {
      await checkAppAccess(ctx, input.applicationId);

      // Unset all other primary domains for this app
      await ctx.db
        .update(domains)
        .set({ isPrimary: false })
        .where(eq(domains.applicationId, input.applicationId));

      // Set selected domain as primary
      const [updated] = await ctx.db
        .update(domains)
        .set({ isPrimary: true, updatedAt: new Date() })
        .where(
          and(
            eq(domains.id, input.id),
            eq(domains.applicationId, input.applicationId)
          )
        )
        .returning();

      if (!updated) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Domain not found",
        });
      }

      return updated;
    }),

  // Remove a domain
  remove: protectedProcedure
    .input(z.object({ id: z.string().uuid(), applicationId: z.string().uuid() }))
    .mutation(async ({ ctx, input }) => {
      await checkAppAccess(ctx, input.applicationId);

      const domain = await ctx.db.query.domains.findFirst({
        where: and(
          eq(domains.id, input.id),
          eq(domains.applicationId, input.applicationId)
        ),
      });

      if (!domain) {
        throw new TRPCError({
          code: "NOT_FOUND",
          message: "Domain not found",
        });
      }

      await ctx.db.delete(domains).where(eq(domains.id, input.id));

      return { success: true };
    }),

  // Get certificate/SSL status for domains
  getCertificateStatus: protectedProcedure
    .input(z.object({ applicationId: z.string().uuid() }))
    .query(async ({ ctx, input }) => {
      await checkAppAccess(ctx, input.applicationId);

      const appDomains = await ctx.db.query.domains.findMany({
        where: eq(domains.applicationId, input.applicationId),
      });

      return appDomains.map((domain) => {
        const isLocal = isLocalhostDomain(domain.domain);

        if (isLocal) {
          return {
            domainId: domain.id,
            domain: domain.domain,
            sslStatus: "not_applicable" as const,
            sslMessage: "SSL is not required for localhost/local domains",
            isLocal: true,
          };
        }

        // For real domains, Traefik handles certificate provisioning via ACME
        // Certificate status is determined by whether the domain is active + verified
        if (!domain.verified) {
          return {
            domainId: domain.id,
            domain: domain.domain,
            sslStatus: "pending_verification" as const,
            sslMessage: "Domain must be verified before SSL can be provisioned",
            isLocal: false,
          };
        }

        return {
          domainId: domain.id,
          domain: domain.domain,
          sslStatus: "active" as const,
          sslMessage: "SSL certificate auto-managed by Let's Encrypt via Traefik",
          isLocal: false,
        };
      });
    }),

  // Get the access URL for an application (primary domain or localhost:port)
  getAccessUrl: protectedProcedure
    .input(z.object({ applicationId: z.string().uuid() }))
    .query(async ({ ctx, input }) => {
      await checkAppAccess(ctx, input.applicationId);

      // First check for a primary domain
      const primaryDomain = await ctx.db.query.domains.findFirst({
        where: and(
          eq(domains.applicationId, input.applicationId),
          eq(domains.isPrimary, true),
          eq(domains.status, "active")
        ),
      });

      if (primaryDomain) {
        const protocol = primaryDomain.forceHttps ? "https" : "http";
        return {
          url: `${protocol}://${primaryDomain.domain}`,
          type: "domain" as const,
          domain: primaryDomain.domain,
        };
      }

      // Check for any active domain
      const anyDomain = await ctx.db.query.domains.findFirst({
        where: and(
          eq(domains.applicationId, input.applicationId),
          eq(domains.status, "active")
        ),
      });

      if (anyDomain) {
        const protocol = anyDomain.forceHttps ? "https" : "http";
        return {
          url: `${protocol}://${anyDomain.domain}`,
          type: "domain" as const,
          domain: anyDomain.domain,
        };
      }

      // Fallback: no domain, try to get port from container
      return {
        url: null,
        type: "none" as const,
        domain: null,
      };
    }),
});
