import * as fs from "fs";
import * as path from "path";
import { db, domains } from "@guildserver/database";
import { eq, and } from "drizzle-orm";
import { logger } from "../utils/logger";

const TRAEFIK_DYNAMIC_DIR =
  process.env.TRAEFIK_DYNAMIC_DIR || "/etc/traefik/dynamic";

const DYNAMIC_FILE_NAME = "custom-domains.yml";

/**
 * Synchronize all verified custom domains directly into Traefik's dynamic
 * file configuration.
 *
 * Traefik watches this directory with `--providers.file.watch=true` and
 * updates its router rules instantly (under 10ms) without restarting any
 * containers or requiring an application redeploy.
 */
export async function syncTraefikDynamicDomains(): Promise<void> {
  try {
    const dynamicDir = path.resolve(TRAEFIK_DYNAMIC_DIR);

    // If the directory does not exist, try to create it
    if (!fs.existsSync(dynamicDir)) {
      try {
        fs.mkdirSync(dynamicDir, { recursive: true });
      } catch (mkdirErr) {
        logger.warn(
          `[traefik-dynamic] Traefik dynamic directory ${dynamicDir} does not exist and could not be created: ${(mkdirErr as Error).message}`
        );
        return;
      }
    }

    // Query all verified and active domains associated with applications
    const activeDomains = await db.query.domains.findMany({
      where: and(eq(domains.verified, true), eq(domains.status, "active")),
      with: {
        application: true,
      },
    });

    const lines: string[] = [
      "# Auto-generated by GuildServer for dynamic custom domain routing",
      "# Do not edit manually — changes will be overwritten",
      "http:",
      "  routers:",
    ];

    let count = 0;
    for (const d of activeDomains) {
      if (!d.application?.name) continue;
      const domainName = d.domain.trim();
      if (!domainName) continue;

      const routerKey = `custom-domain-${d.id.replace(/[^a-zA-Z0-9_-]/g, "_")}`;
      const serviceName = `${d.application.name.replace(/[^a-zA-Z0-9]/g, "-").toLowerCase()}@docker`;
      lines.push(`    ${routerKey}:`);
      lines.push(`      rule: "Host(\`${domainName}\`)"`);
      lines.push(`      service: "${serviceName}"`);
      lines.push(`      entryPoints:`);
      lines.push(`        - "web"`);
      lines.push(`        - "websecure"`);
      count++;
    }

    if (count === 0) {
      lines.push("    {}");
    }

    const content = lines.join("\n") + "\n";
    const targetFile = path.join(dynamicDir, DYNAMIC_FILE_NAME);
    const tempFile = path.join(dynamicDir, `.${DYNAMIC_FILE_NAME}.tmp`);

    // Atomic write
    fs.writeFileSync(tempFile, content, "utf8");
    fs.renameSync(tempFile, targetFile);

    logger.info(
      `[traefik-dynamic] Synchronized ${count} custom domain router(s) to ${targetFile}`
    );
  } catch (error) {
    logger.error(
      `[traefik-dynamic] Failed to synchronize custom domains to Traefik: ${(error as Error).message}`
    );
  }
}
