/**
 * Deterministic total order for every SQL file under `../migrations/`.
 *
 * BACKGROUND
 * ----------
 * This package's `migrations/` folder holds two independently-numbered
 * families of files that were never reconciled into one sequence:
 *
 *  - "drizzle"  — generated by `drizzle-kit generate:pg`, named with a
 *                 random codename (e.g. `0001_mixed_mister_fear.sql`) and
 *                 recorded in `migrations/meta/_journal.json`.
 *  - "hand"     — written by hand alongside a feature PR, named
 *                 descriptively (e.g. `0009_registry_credentials.sql`),
 *                 and NEVER added to the journal.
 *
 * Both families reuse the same numeric prefixes (there are two files named
 * `0004_*`, two named `0003_*`, etc.), so the numeric prefix alone is not a
 * valid sort key and cannot be used to decide execution order.
 *
 * CHOSEN ORDER: drizzle family first (in journal/generation order), then
 * hand family (in numeric order). Rationale, verified against the actual
 * file contents and git history before picking this:
 *
 *  1. The drizzle-generated files were authored by diffing the *current*
 *     `schema/index.ts` (which already contained the hand-written columns)
 *     against drizzle's own migration history (which only knew about
 *     `0000_moaning_dragon_man`). That is why e.g. `0001_mixed_mister_fear`
 *     independently re-adds `applications.container_port`,
 *     `deployments.image_tag`, the `webhook_deliveries` table, etc. — the
 *     exact same objects the hand-written `0002`/`0003`/`0004`/`0005`
 *     migrations add. Both `drizzle.__drizzle_migrations` on the shared
 *     test DB and the production database show exactly 4 successfully
 *     applied rows matching `0000`-`0003` with NO errors, which is only
 *     possible if those columns did not already exist when the drizzle
 *     migrations ran — i.e. drizzle 0000-0003 really did run *before* any
 *     of the colliding hand migrations, in production history.
 *  2. `0002_parallel_sunspot` (drizzle) adds
 *     `applications.registry_url/registry_username/registry_password`
 *     with plain `ADD COLUMN` (no guard). `0009_registry_credentials`
 *     (hand) adds the exact same three columns, but guarded with
 *     `IF NOT EXISTS`. If the hand file ran first, the later drizzle
 *     `ADD COLUMN` would fail outright on re-play. Ordering drizzle before
 *     hand is the only order that tolerates both being replayed.
 *  3. No hand-written migration is a structural prerequisite of a later
 *     drizzle-generated one (checked directly: nothing in the drizzle
 *     files references a column/table that only a hand migration creates).
 *
 * So: drizzle-before-hand at any shared numeric prefix is both what
 * actually happened in production and the only order that is safe to
 * replay against a database that already has one family (or both)
 * applied. Everything is additionally made idempotent (see the runner and
 * the `IF NOT EXISTS` / `DO $$ ... EXCEPTION WHEN duplicate_object`
 * guards added to the SQL files themselves) so a family's internal order
 * no longer depends on strict adjacency, only on this list.
 *
 * Anyone adding a new migration going forward should append it to the end
 * of this list with a numeric id one higher than the current max, and
 * skip the two-family split entirely.
 */

export type MigrationFamily = "drizzle" | "hand";

export interface MigrationManifestEntry {
  /** Unique, stable identifier. Matches the SQL filename without the extension. */
  id: string;
  /** Filename under packages/database/migrations/. */
  file: string;
  family: MigrationFamily;
  /**
   * For "drizzle" entries only: the epoch-ms `when` value from
   * migrations/meta/_journal.json, used to reconcile against rows already
   * recorded by drizzle-orm's own migrator in `drizzle.__drizzle_migrations`.
   */
  journalWhen?: number;
}

export const MIGRATIONS: MigrationManifestEntry[] = [
  // --- drizzle family, in journal order ---
  { id: "0000_moaning_dragon_man", file: "0000_moaning_dragon_man.sql", family: "drizzle", journalWhen: 1754351481606 },
  { id: "0001_mixed_mister_fear", file: "0001_mixed_mister_fear.sql", family: "drizzle", journalWhen: 1781428934625 },
  { id: "0002_parallel_sunspot", file: "0002_parallel_sunspot.sql", family: "drizzle", journalWhen: 1781884772346 },
  { id: "0003_late_chronomancer", file: "0003_late_chronomancer.sql", family: "drizzle", journalWhen: 1782053508349 },
  { id: "0004_condemned_mad_thinker", file: "0004_condemned_mad_thinker.sql", family: "drizzle" },

  // --- hand-written family, in numeric order ---
  { id: "0001_add_performance_indexes", file: "0001_add_performance_indexes.sql", family: "hand" },
  { id: "0002_add_container_port", file: "0002_add_container_port.sql", family: "hand" },
  { id: "0003_deployment_rollback", file: "0003_deployment_rollback.sql", family: "hand" },
  { id: "0004_preview_deployments", file: "0004_preview_deployments.sql", family: "hand" },
  { id: "0005_webhook_deliveries", file: "0005_webhook_deliveries.sql", family: "hand" },
  { id: "0006_notifications", file: "0006_notifications.sql", family: "hand" },
  { id: "0007_compute_providers", file: "0007_compute_providers.sql", family: "hand" },
  { id: "0008_deployment_provider_metadata", file: "0008_deployment_provider_metadata.sql", family: "hand" },
  { id: "0009_registry_credentials", file: "0009_registry_credentials.sql", family: "hand" },
  { id: "0010_billing_quotes_core", file: "0010_billing_quotes_core.sql", family: "hand" },
  { id: "0011_app_persistent_storage", file: "0011_app_persistent_storage.sql", family: "hand" },
];

export function findMigration(id: string): MigrationManifestEntry | undefined {
  return MIGRATIONS.find((m) => m.id === id);
}
