// Shared template catalog and UI metadata for the templates page.

export type SourceKind = "docker" | "git"
export type TemplateTrack = "ai" | "open-source" | "starter" | "production" | "ops"

export type LogoSpec = {
  slug: string
  label: string
  fallbackIcon?: string
}

export interface Template {
  id: string
  name: string
  description: string
  icon: string
  category: string
  tags: string[]
  popular?: boolean
  useCase: string[]
  framework?: string
  track?: TemplateTrack
  // Docker templates (sourceKind === "docker")
  sourceKind: SourceKind
  dockerImage?: string
  containerPort?: number
  envVars?: Record<string, string>
  // Git templates (sourceKind === "git")
  repository?: string
  branch?: string
  buildPath?: string
  buildType?: string
}

// ─── Filter definitions ─────────────────────────────────────────────────────

export interface FilterSection {
  id: string
  label: string
  options: string[]
}

export const USE_CASE_LABELS: Record<string, string> = {
  AI: "AI apps",
  Automation: "Automation",
  Backend: "Backend apps",
  Blog: "Blogs",
  CMS: "CMS",
  Database: "Databases",
  Ecommerce: "E-commerce",
  Monitoring: "Monitoring",
  Portfolio: "Portfolios",
  SaaS: "SaaS",
  Security: "Security",
  Starter: "Starter kits",
}

export const USE_CASE_PRIORITY = [
  "AI",
  "Starter",
  "SaaS",
  "Backend",
  "Database",
  "Monitoring",
  "Blog",
  "CMS",
  "Ecommerce",
  "Portfolio",
  "Security",
  "Automation",
]

export const SOURCE_LABELS: Record<SourceKind, string> = {
  docker: "Docker image",
  git: "Open source",
}

export const TRACK_LABELS: Record<TemplateTrack, string> = {
  ai: "AI",
  "open-source": "Open source",
  starter: "Starter",
  production: "Production",
  ops: "Ops",
}

export const TEMPLATE_LOGOS: Record<string, LogoSpec> = {
  nginx: { slug: "nginx", label: "Nginx", fallbackIcon: "Globe" },
  caddy: { slug: "caddy", label: "Caddy", fallbackIcon: "Globe" },
  postgres: { slug: "postgresql", label: "PostgreSQL", fallbackIcon: "Database" },
  redis: { slug: "redis", label: "Redis", fallbackIcon: "Database" },
  mysql: { slug: "mysql", label: "MySQL", fallbackIcon: "Database" },
  mongodb: { slug: "mongodb", label: "MongoDB", fallbackIcon: "Database" },
  mariadb: { slug: "mariadb", label: "MariaDB", fallbackIcon: "Database" },
  grafana: { slug: "grafana", label: "Grafana", fallbackIcon: "Boxes" },
  "uptime-kuma": { slug: "uptimekuma", label: "Uptime Kuma", fallbackIcon: "Boxes" },
  minio: { slug: "minio", label: "MinIO", fallbackIcon: "Server" },
  rabbitmq: { slug: "rabbitmq", label: "RabbitMQ", fallbackIcon: "Server" },
  ghost: { slug: "ghost", label: "Ghost", fallbackIcon: "Globe" },
  wordpress: { slug: "wordpress", label: "WordPress", fallbackIcon: "Globe" },
  plausible: { slug: "plausibleanalytics", label: "Plausible Analytics", fallbackIcon: "Boxes" },
  n8n: { slug: "n8n", label: "n8n", fallbackIcon: "Boxes" },
  gitea: { slug: "gitea", label: "Gitea", fallbackIcon: "Code2" },
  drone: { slug: "drone", label: "Drone CI", fallbackIcon: "Boxes" },
  portainer: { slug: "portainer", label: "Portainer", fallbackIcon: "Boxes" },
  directus: { slug: "directus", label: "Directus", fallbackIcon: "Server" },
  strapi: { slug: "strapi", label: "Strapi", fallbackIcon: "Server" },
  nextjs: { slug: "nextdotjs", label: "Next.js", fallbackIcon: "Code2" },
  astro: { slug: "astro", label: "Astro", fallbackIcon: "Code2" },
  "astro-ssr": { slug: "astro", label: "Astro", fallbackIcon: "Code2" },
  svelte: { slug: "svelte", label: "Svelte", fallbackIcon: "Code2" },
  nuxt: { slug: "nuxt", label: "Nuxt", fallbackIcon: "Code2" },
  remix: { slug: "remix", label: "Remix", fallbackIcon: "Code2" },
  vuejs: { slug: "vuedotjs", label: "Vue.js", fallbackIcon: "Code2" },
  vite: { slug: "vite", label: "Vite", fallbackIcon: "Code2" },
  django: { slug: "django", label: "Django", fallbackIcon: "Code2" },
  flask: { slug: "flask", label: "Flask", fallbackIcon: "Code2" },
  nestjs: { slug: "nestjs", label: "NestJS", fallbackIcon: "Server" },
  "go-fiber": { slug: "go", label: "Go Fiber", fallbackIcon: "Code2" },
  "deno-app": { slug: "deno", label: "Deno", fallbackIcon: "Server" },
  solidjs: { slug: "solid", label: "SolidJS", fallbackIcon: "Code2" },
  preact: { slug: "preact", label: "Preact", fallbackIcon: "Code2" },
  qwik: { slug: "qwik", label: "Qwik", fallbackIcon: "Code2" },
  "11ty": { slug: "eleventy", label: "Eleventy", fallbackIcon: "Globe" },
  lit: { slug: "lit", label: "Lit", fallbackIcon: "Code2" },
  "static-html": { slug: "html5", label: "Static HTML", fallbackIcon: "Globe" },
  "official-ai-chatgpt": { slug: "nextdotjs", label: "Next.js", fallbackIcon: "Code2" },
  "official-blog-starter": { slug: "nextdotjs", label: "Next.js", fallbackIcon: "Globe" },
  "official-hono-ai-sdk": { slug: "hono", label: "Hono", fallbackIcon: "Code2" },
  "official-ai-vibe-coding-ide": { slug: "nextdotjs", label: "Next.js", fallbackIcon: "Code2" },
  "official-ai-hono-mcp": { slug: "hono", label: "Hono", fallbackIcon: "Code2" },
  "official-express-ai": { slug: "express", label: "Express", fallbackIcon: "Code2" },
  "official-platforms-supabase": { slug: "supabase", label: "Supabase", fallbackIcon: "Boxes" },
  "official-web3-auth": { slug: "nextdotjs", label: "Next.js", fallbackIcon: "Code2" },
  "official-cron": { slug: "nextdotjs", label: "Next.js", fallbackIcon: "Code2" },
  "official-monorepo": { slug: "turbo", label: "Turborepo", fallbackIcon: "Boxes" },
  "official-open-source-node-hello": { slug: "nodedotjs", label: "Node.js", fallbackIcon: "Code2" },
  "official-open-source-slackbot": { slug: "slack", label: "Slack", fallbackIcon: "Boxes" },
  fastify: { slug: "fastify", label: "Fastify", fallbackIcon: "Server" },
  "official-open-source-express": { slug: "express", label: "Express", fallbackIcon: "Code2" },
  "official-open-source-fastapi": { slug: "fastapi", label: "FastAPI", fallbackIcon: "Code2" },
  "official-ai-litellm-gateway": { slug: "fastapi", label: "FastAPI", fallbackIcon: "Boxes" },
  "official-ai-mcp-wrapper": { slug: "hono", label: "Hono", fallbackIcon: "Boxes" },
  "official-open-source-reuse-responses": { slug: "nextdotjs", label: "Next.js", fallbackIcon: "Code2" },
  "official-open-source-next-fastapi-monorepo": { slug: "nextdotjs", label: "Next.js", fallbackIcon: "Boxes" },
  "official-open-source-saas-microservices": { slug: "nextdotjs", label: "Next.js", fallbackIcon: "Boxes" },
  "official-open-source-microfrontends": { slug: "nextdotjs", label: "Next.js", fallbackIcon: "Boxes" },
  "official-open-source-flask": { slug: "flask", label: "Flask", fallbackIcon: "Code2" },
  "official-open-source-django": { slug: "django", label: "Django", fallbackIcon: "Code2" },
  "official-open-source-go-api": { slug: "go", label: "Go", fallbackIcon: "Code2" },
  "official-open-source-go-gin": { slug: "go", label: "Go", fallbackIcon: "Code2" },
}

export const getFilterLabel = (sectionId: string, option: string) => {
  if (sectionId === "useCase") return USE_CASE_LABELS[option] || option
  if (sectionId === "track") return TRACK_LABELS[option as TemplateTrack] || option
  if (sectionId === "sourceKind") return SOURCE_LABELS[option as SourceKind] || option
  return option
}

export const getTrackLabel = (track: TemplateTrack) => TRACK_LABELS[track] || track

export const getLogoSpec = (template: Template): LogoSpec => {
  return (
    TEMPLATE_LOGOS[template.id] ||
    (template.framework ? TEMPLATE_LOGOS[template.framework.toLowerCase()] : undefined) ||
    {
      slug: template.sourceKind === "git" ? "github" : "docker",
      label: template.name,
      fallbackIcon: template.icon === "boxes" ? "Boxes" : "Code2",
    }
  )
}

// ─── Template catalogue ──────────────────────────────────────────────────────

export const TEMPLATES: Template[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  //  DOCKER IMAGES — ready-to-run services
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "nginx",
    name: "Nginx",
    description: "High-performance web server and reverse proxy",
    icon: "globe",
    category: "Web Servers",
    sourceKind: "docker",
    track: "ops",
    dockerImage: "nginx:alpine",
    containerPort: 80,
    tags: ["web server", "proxy", "static"],
    useCase: ["Backend", "Starter"],
    popular: true,
  },
  {
    id: "caddy",
    name: "Caddy",
    description: "Web server with automatic HTTPS",
    icon: "globe",
    category: "Web Servers",
    sourceKind: "docker",
    track: "ops",
    dockerImage: "caddy:2-alpine",
    containerPort: 80,
    tags: ["web server", "https", "proxy"],
    useCase: ["Backend"],
  },
  {
    id: "postgres",
    name: "PostgreSQL",
    description: "Advanced open-source relational database",
    icon: "database",
    category: "Databases",
    sourceKind: "docker",
    track: "ops",
    dockerImage: "postgres:16-alpine",
    containerPort: 5432,
    envVars: { POSTGRES_DB: "app", POSTGRES_USER: "admin", POSTGRES_PASSWORD: "changeme" },
    tags: ["database", "sql", "relational"],
    useCase: ["Database"],
    popular: true,
  },
  {
    id: "redis",
    name: "Redis",
    description: "In-memory data store for caching and messaging",
    icon: "database",
    category: "Databases",
    sourceKind: "docker",
    track: "ops",
    dockerImage: "redis:7-alpine",
    containerPort: 6379,
    tags: ["cache", "queue", "key-value"],
    useCase: ["Database"],
    popular: true,
  },
  {
    id: "mysql",
    name: "MySQL",
    description: "Popular open-source relational database",
    icon: "database",
    category: "Databases",
    sourceKind: "docker",
    track: "ops",
    dockerImage: "mysql:8",
    containerPort: 3306,
    envVars: { MYSQL_ROOT_PASSWORD: "changeme", MYSQL_DATABASE: "app" },
    tags: ["database", "sql", "relational"],
    useCase: ["Database"],
  },
  {
    id: "mongodb",
    name: "MongoDB",
    description: "Document-oriented NoSQL database",
    icon: "database",
    category: "Databases",
    sourceKind: "docker",
    track: "ops",
    dockerImage: "mongo:7",
    containerPort: 27017,
    tags: ["database", "nosql", "document"],
    useCase: ["Database"],
  },
  {
    id: "mariadb",
    name: "MariaDB",
    description: "Community-developed fork of MySQL",
    icon: "database",
    category: "Databases",
    sourceKind: "docker",
    track: "ops",
    dockerImage: "mariadb:11",
    containerPort: 3306,
    envVars: { MARIADB_ROOT_PASSWORD: "changeme", MARIADB_DATABASE: "app" },
    tags: ["database", "sql", "mysql-compatible"],
    useCase: ["Database"],
  },
  {
    id: "grafana",
    name: "Grafana",
    description: "Open-source analytics and monitoring platform",
    icon: "boxes",
    category: "Monitoring",
    sourceKind: "docker",
    track: "ops",
    dockerImage: "grafana/grafana:latest",
    containerPort: 3000,
    tags: ["monitoring", "dashboards", "analytics"],
    useCase: ["Monitoring"],
  },
  {
    id: "uptime-kuma",
    name: "Uptime Kuma",
    description: "Self-hosted monitoring tool like Uptime Robot",
    icon: "boxes",
    category: "Monitoring",
    sourceKind: "docker",
    track: "ops",
    dockerImage: "louislam/uptime-kuma:1",
    containerPort: 3001,
    tags: ["monitoring", "uptime", "status page"],
    useCase: ["Monitoring"],
    popular: true,
  },
  {
    id: "minio",
    name: "MinIO",
    description: "S3-compatible object storage server",
    icon: "server",
    category: "Storage",
    sourceKind: "docker",
    track: "ops",
    dockerImage: "minio/minio:latest",
    containerPort: 9000,
    envVars: { MINIO_ROOT_USER: "admin", MINIO_ROOT_PASSWORD: "changeme123" },
    tags: ["storage", "s3", "object store"],
    useCase: ["Backend"],
  },
  {
    id: "rabbitmq",
    name: "RabbitMQ",
    description: "Open-source message broker with management UI",
    icon: "server",
    category: "Messaging",
    sourceKind: "docker",
    track: "ops",
    dockerImage: "rabbitmq:3-management-alpine",
    containerPort: 15672,
    envVars: { RABBITMQ_DEFAULT_USER: "admin", RABBITMQ_DEFAULT_PASS: "changeme" },
    tags: ["messaging", "queue", "amqp"],
    useCase: ["Backend"],
  },
  {
    id: "ghost",
    name: "Ghost",
    description: "Professional publishing platform for blogs",
    icon: "globe",
    category: "CMS",
    sourceKind: "docker",
    track: "production",
    dockerImage: "ghost:5-alpine",
    containerPort: 2368,
    envVars: { NODE_ENV: "production" },
    tags: ["blog", "cms", "publishing"],
    useCase: ["Blog", "CMS"],
    popular: true,
  },
  {
    id: "wordpress",
    name: "WordPress",
    description: "Most popular content management system",
    icon: "globe",
    category: "CMS",
    sourceKind: "docker",
    track: "production",
    dockerImage: "wordpress:6-apache",
    containerPort: 80,
    envVars: { WORDPRESS_DB_HOST: "db:3306", WORDPRESS_DB_USER: "wp", WORDPRESS_DB_PASSWORD: "changeme" },
    tags: ["cms", "blog", "php"],
    useCase: ["Blog", "CMS", "Ecommerce"],
  },
  {
    id: "plausible",
    name: "Plausible Analytics",
    description: "Privacy-friendly Google Analytics alternative",
    icon: "boxes",
    category: "Analytics",
    sourceKind: "docker",
    track: "ops",
    dockerImage: "plausible/analytics:latest",
    containerPort: 8000,
    envVars: { BASE_URL: "http://localhost", SECRET_KEY_BASE: "changeme-generate-a-secret" },
    tags: ["analytics", "privacy", "web"],
    useCase: ["Monitoring"],
  },
  {
    id: "n8n",
    name: "n8n",
    description: "Workflow automation tool with 200+ integrations",
    icon: "boxes",
    category: "Automation",
    sourceKind: "docker",
    track: "ops",
    dockerImage: "n8nio/n8n:latest",
    containerPort: 5678,
    tags: ["automation", "workflow", "integrations"],
    useCase: ["Backend", "AI"],
  },
  {
    id: "gitea",
    name: "Gitea",
    description: "Lightweight self-hosted Git service",
    icon: "code",
    category: "Developer Tools",
    sourceKind: "docker",
    track: "open-source",
    dockerImage: "gitea/gitea:latest",
    containerPort: 3000,
    tags: ["git", "version control", "devops"],
    useCase: ["Backend"],
  },
  {
    id: "drone",
    name: "Drone CI",
    description: "Container-native continuous integration",
    icon: "boxes",
    category: "Developer Tools",
    sourceKind: "docker",
    track: "ops",
    dockerImage: "drone/drone:latest",
    containerPort: 80,
    tags: ["ci", "cd", "devops"],
    useCase: ["Backend"],
  },
  {
    id: "portainer",
    name: "Portainer",
    description: "Docker management UI for containers and clusters",
    icon: "boxes",
    category: "Developer Tools",
    sourceKind: "docker",
    track: "ops",
    dockerImage: "portainer/portainer-ce:latest",
    containerPort: 9000,
    tags: ["docker", "management", "ui"],
    useCase: ["Monitoring"],
  },
  {
    id: "directus",
    name: "Directus",
    description: "Instant REST + GraphQL API for any SQL database",
    icon: "server",
    category: "CMS",
    sourceKind: "docker",
    track: "production",
    dockerImage: "directus/directus:latest",
    containerPort: 8055,
    envVars: { KEY: "changeme", SECRET: "changeme", ADMIN_EMAIL: "admin@example.com", ADMIN_PASSWORD: "changeme" },
    tags: ["headless cms", "api", "database"],
    useCase: ["CMS", "Backend"],
  },
  {
    id: "strapi",
    name: "Strapi",
    description: "Open-source headless CMS for building APIs",
    icon: "server",
    category: "CMS",
    sourceKind: "docker",
    track: "production",
    dockerImage: "strapi/strapi:latest",
    containerPort: 1337,
    tags: ["headless cms", "api", "node"],
    useCase: ["CMS", "Backend"],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  //  GIT TEMPLATES — GuildServer examples
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: "nextjs",
    name: "Next.js",
    description: "React framework with SSR, routing, and API routes",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "nextjs",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["react", "ssr", "javascript", "fullstack"],
    useCase: ["Starter", "SaaS"],
    framework: "Next.js",
    popular: true,
  },
  {
    id: "astro",
    name: "Astro",
    description: "Content-driven framework for fast, modern websites",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "astro",
    buildType: "nixpacks",
    containerPort: 4321,
    tags: ["static", "ssr", "javascript", "content"],
    useCase: ["Blog", "Portfolio", "Starter"],
    framework: "Astro",
    popular: true,
  },
  {
    id: "astro-ssr",
    name: "Astro SSR",
    description: "Astro with server-side rendering enabled",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "astro-ssr",
    buildType: "nixpacks",
    containerPort: 4321,
    tags: ["astro", "ssr", "javascript", "dynamic"],
    useCase: ["Starter"],
    framework: "Astro",
  },
  {
    id: "svelte",
    name: "Svelte",
    description: "Cybernetically enhanced web framework",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "svelte",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["svelte", "ssr", "javascript", "fullstack"],
    useCase: ["Starter"],
    framework: "Svelte",
  },
  {
    id: "nuxt",
    name: "Nuxt",
    description: "Full-stack Vue.js framework with SSR support",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "nuxt",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["vue", "ssr", "javascript", "fullstack"],
    useCase: ["Starter", "SaaS"],
    framework: "Nuxt",
  },
  {
    id: "remix",
    name: "Remix",
    description: "Full-stack React framework focused on web standards",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "remix",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["react", "ssr", "javascript", "web standards"],
    useCase: ["Starter"],
    framework: "Remix",
  },
  {
    id: "vuejs",
    name: "Vue.js",
    description: "Progressive JavaScript framework for building UIs",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "vuejs",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["vue", "spa", "javascript", "frontend"],
    useCase: ["Starter"],
    framework: "Vue",
  },
  {
    id: "vite",
    name: "Vite",
    description: "Fast frontend build tool with HMR and optimized builds",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "vite",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["react", "vite", "javascript", "frontend"],
    useCase: ["Starter"],
    framework: "Vite",
  },
  {
    id: "django",
    name: "Django",
    description: "High-level Python web framework for rapid development",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "Django-Example",
    buildType: "nixpacks",
    containerPort: 8000,
    tags: ["python", "django", "api", "fullstack"],
    useCase: ["Backend", "SaaS"],
    framework: "Django",
    popular: true,
  },
  {
    id: "flask",
    name: "Flask",
    description: "Lightweight Python WSGI web application framework",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "Flask-Example",
    buildType: "nixpacks",
    containerPort: 5000,
    tags: ["python", "flask", "api", "microservice"],
    useCase: ["Backend"],
    framework: "Flask",
  },
  {
    id: "nestjs",
    name: "NestJS",
    description: "Progressive Node.js framework for enterprise APIs",
    icon: "server",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "nestjs",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["node", "nestjs", "typescript", "api"],
    useCase: ["Backend", "SaaS"],
    framework: "NestJS",
  },
  {
    id: "go-fiber",
    name: "Go Fiber",
    description: "Express-inspired Go web framework built on Fasthttp",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "go-fiber",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["go", "golang", "fiber", "api"],
    useCase: ["Backend"],
    framework: "Go",
  },
  {
    id: "deno-app",
    name: "Deno",
    description: "Secure TypeScript runtime with built-in tooling",
    icon: "server",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "deno",
    buildType: "nixpacks",
    containerPort: 8000,
    tags: ["deno", "typescript", "runtime", "secure"],
    useCase: ["Backend"],
    framework: "Deno",
  },
  {
    id: "solidjs",
    name: "SolidJS",
    description: "Simple and performant reactive JavaScript framework",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "solidjs",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["solid", "reactive", "javascript", "frontend"],
    useCase: ["Starter"],
    framework: "SolidJS",
  },
  {
    id: "preact",
    name: "Preact",
    description: "Fast 3kB alternative to React with the same API",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "preact",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["preact", "react", "lightweight", "frontend"],
    useCase: ["Starter"],
    framework: "Preact",
  },
  {
    id: "qwik",
    name: "Qwik",
    description: "Resumable framework for instant-loading web apps",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "qwik",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["qwik", "resumable", "javascript", "performance"],
    useCase: ["Starter"],
    framework: "Qwik",
  },
  {
    id: "t3-stack",
    name: "T3 Stack",
    description: "Next.js + tRPC + Prisma + Tailwind full-stack starter",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "t3",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["next", "trpc", "prisma", "fullstack"],
    useCase: ["SaaS", "Starter"],
    framework: "Next.js",
  },
  {
    id: "11ty",
    name: "Eleventy (11ty)",
    description: "Simple and flexible static site generator",
    icon: "globe",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "11ty",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["static", "ssg", "javascript", "content"],
    useCase: ["Blog", "Portfolio"],
    framework: "Eleventy",
  },
  {
    id: "lit",
    name: "Lit",
    description: "Simple library for building fast web components",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "lit",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["web components", "lit", "javascript", "lightweight"],
    useCase: ["Starter"],
    framework: "Lit",
  },
  {
    id: "static-html",
    name: "Static HTML",
    description: "Simple static HTML website",
    icon: "globe",
    category: "Web Servers",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "html",
    buildType: "nixpacks",
    containerPort: 80,
    tags: ["html", "static", "simple", "beginner"],
    useCase: ["Starter", "Portfolio"],
  },
  {
    id: "official-ai-chatgpt",
    name: "AI ChatGPT App",
    description: "An open-source AI chatbot app template built with Next.js",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/solutions/ai-chatgpt",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["nextjs", "ai", "chatgpt", "openai"],
    useCase: ["AI", "Starter"],
    framework: "Next.js",
    track: "ai",
    popular: true,
  },
  {
    id: "official-blog-starter",
    name: "Blog Starter Kit",
    description: "A statically generated blog example using Next.js and Markdown",
    icon: "globe",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/solutions/blog",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["nextjs", "blog", "markdown"],
    useCase: ["Blog", "Starter"],
    framework: "Next.js",
    track: "open-source",
  },
  {
    id: "official-hono-ai-sdk",
    name: "Hono AI SDK Starter",
    description: "A starter for Hono with the AI SDK",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/starter/hono-ai-sdk",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["hono", "ai", "sdk"],
    useCase: ["AI", "Starter", "Backend"],
    framework: "Hono",
    track: "ai",
  },
  {
    id: "official-ai-vibe-coding-ide",
    name: "Vibe Coding IDE",
    description: "An AI-assisted coding workspace for building and iterating faster",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/python/vibe-coding-ide",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["ai", "ide", "coding", "fullstack"],
    useCase: ["AI", "Starter", "Backend"],
    framework: "Next.js",
    track: "ai",
    popular: true,
  },
  {
    id: "official-ai-hono-mcp",
    name: "Hono MCP Starter",
    description: "A lightweight Hono starter for agent tools and MCP endpoints",
    icon: "boxes",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/starter/hono-mcp",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["ai", "mcp", "hono", "agent"],
    useCase: ["AI", "Starter", "Backend"],
    framework: "Hono",
    track: "ai",
  },
  {
    id: "official-express-ai",
    name: "Express AI Chatbot",
    description: "A lightweight Express API integrating with AI SDK",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/starter/express-ai-sdk",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["express", "node", "ai"],
    useCase: ["AI", "Backend"],
    framework: "Express",
    track: "ai",
  },
  {
    id: "official-ai-litellm-gateway",
    name: "LiteLLM Gateway",
    description: "An open-source gateway for routing requests across LLM providers",
    icon: "server",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/python/litellm-gateway",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["ai", "llm", "gateway", "open source"],
    useCase: ["AI", "Backend"],
    framework: "FastAPI",
    track: "ai",
    popular: true,
  },
  {
    id: "official-ai-mcp-wrapper",
    name: "MCP API Wrapper",
    description: "A starter for building agent-ready APIs and tool wrappers",
    icon: "boxes",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/starter/mcp-api-wrapper",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["ai", "mcp", "agent", "open source"],
    useCase: ["AI", "Starter", "Backend"],
    framework: "Hono",
    track: "ai",
  },
  {
    id: "official-open-source-reuse-responses",
    name: "Reusing Responses",
    description: "A Next.js example for caching and reusing shared responses",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/solutions/reuse-responses",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["nextjs", "cache", "performance", "open source"],
    useCase: ["Starter", "Backend"],
    framework: "Next.js",
    track: "open-source",
  },
  {
    id: "official-platforms-supabase",
    name: "Platforms Starter (Supabase)",
    description: "Multi-tenant platform builder using Next.js and Supabase",
    icon: "boxes",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/solutions/platforms-slate-supabase",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["nextjs", "supabase", "multi-tenant"],
    useCase: ["SaaS", "Starter", "Database"],
    framework: "Next.js",
    track: "open-source",
    popular: true,
  },
  {
    id: "official-open-source-next-fastapi-monorepo",
    name: "Next + FastAPI Monorepo",
    description: "A split frontend and backend template for full-stack teams",
    icon: "boxes",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/python/next-fastapi-monorepo",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["nextjs", "fastapi", "monorepo", "open source"],
    useCase: ["SaaS", "Starter", "Backend"],
    framework: "Next.js",
    track: "production",
  },
  {
    id: "official-open-source-saas-microservices",
    name: "SaaS Microservices",
    description: "A monorepo SaaS architecture split into independent services",
    icon: "boxes",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/solutions/saas-microservices",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["saas", "microservices", "monorepo", "open source"],
    useCase: ["SaaS", "Backend"],
    framework: "Next.js",
    track: "production",
  },
  {
    id: "official-open-source-microfrontends",
    name: "Microfrontends",
    description: "A modular monorepo built for independently deployed frontend teams",
    icon: "boxes",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/solutions/microfrontends",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["microfrontends", "monorepo", "design system", "open source"],
    useCase: ["Starter", "SaaS"],
    framework: "Next.js",
    track: "open-source",
  },
  {
    id: "official-open-source-express",
    name: "Express Starter",
    description: "A minimal open-source Express app with a clean deployment path",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/solutions/express",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["express", "node", "open source", "starter"],
    useCase: ["Backend", "Starter"],
    framework: "Express",
    track: "open-source",
  },
  {
    id: "official-open-source-flask",
    name: "Flask Starter",
    description: "A minimal open-source Python Flask service",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/python/flask",
    buildType: "nixpacks",
    containerPort: 5000,
    tags: ["flask", "python", "api", "open source"],
    useCase: ["Backend"],
    framework: "Flask",
    track: "open-source",
  },
  {
    id: "official-open-source-django",
    name: "Django Starter",
    description: "A practical open-source Django service starter",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/python/django",
    buildType: "nixpacks",
    containerPort: 8000,
    tags: ["django", "python", "web", "open source"],
    useCase: ["Backend", "Starter"],
    framework: "Django",
    track: "open-source",
  },
  {
    id: "official-open-source-go-api",
    name: "Go API",
    description: "A small Go service example for straightforward APIs",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/go/api",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["go", "api", "backend", "open source"],
    useCase: ["Backend"],
    framework: "Go",
    track: "open-source",
  },
  {
    id: "official-open-source-go-gin",
    name: "Go Gin",
    description: "A Go starter built with the Gin web framework",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/go/gin",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["go", "gin", "api", "open source"],
    useCase: ["Backend", "Starter"],
    framework: "Go",
    track: "open-source",
  },
  {
    id: "official-open-source-node-hello",
    name: "Node Hello World",
    description: "The smallest possible open-source Node.js starter",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/solutions/node-hello-world",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["node", "hello world", "starter", "open source"],
    useCase: ["Starter", "Backend"],
    framework: "Node.js",
    track: "open-source",
  },
  {
    id: "official-open-source-slackbot",
    name: "Slackbot",
    description: "An open-source Slack bot starter for lightweight automations",
    icon: "boxes",
    category: "Automation",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/solutions/slackbot",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["slack", "bot", "automation", "open source"],
    useCase: ["Automation", "Backend"],
    framework: "Node.js",
    track: "open-source",
  },
  {
    id: "official-open-source-fastify",
    name: "Fastify Starter",
    description: "A fast open-source Fastify starter with a clean deployment path",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/starter/fastify",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["fastify", "node", "api", "open source"],
    useCase: ["Backend", "Starter"],
    framework: "Fastify",
    track: "open-source",
  },
  {
    id: "official-open-source-fastapi",
    name: "FastAPI Starter",
    description: "A lightweight open-source Python API starter",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/python/fastapi",
    buildType: "nixpacks",
    containerPort: 8000,
    tags: ["fastapi", "python", "open source", "api"],
    useCase: ["Backend"],
    framework: "FastAPI",
    track: "open-source",
  },
  {
    id: "official-web3-auth",
    name: "Web3 Authentication",
    description: "Web3 wallet sign-in and session management",
    icon: "shield",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/solutions/web3-authentication",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["nextjs", "web3", "crypto", "auth"],
    useCase: ["Security", "Starter"],
    framework: "Next.js",
    track: "open-source",
  },
  {
    id: "official-cron",
    name: "Cron Jobs Scheduler",
    description: "Example showing how to run cron jobs in Next.js APIs",
    icon: "code",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/solutions/cron",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["nextjs", "cron", "jobs", "automation"],
    useCase: ["Backend", "Automation"],
    framework: "Next.js",
    track: "open-source",
  },
  {
    id: "official-monorepo",
    name: "Turborepo Next.js Monorepo",
    description: "Advanced Turborepo workspace with shared UI and apps",
    icon: "boxes",
    category: "Frameworks",
    sourceKind: "git",
    repository: "https://github.com/davidpius95/guildserver-examples",
    branch: "main",
    buildPath: "official/solutions/monorepo",
    buildType: "nixpacks",
    containerPort: 3000,
    tags: ["turborepo", "nextjs", "monorepo", "workspace"],
    useCase: ["Starter", "SaaS"],
    framework: "Next.js",
    track: "open-source",
  }
]

// ─── Derive filter sections from the templates ───────────────────────────────

export const FILTER_SECTIONS: FilterSection[] = [
  {
    id: "useCase",
    label: "Purpose",
    options: [...new Set(TEMPLATES.flatMap((t) => t.useCase))].sort((a, b) => {
      const ai = USE_CASE_PRIORITY.indexOf(a)
      const bi = USE_CASE_PRIORITY.indexOf(b)
      if (ai === -1 && bi === -1) return a.localeCompare(b)
      if (ai === -1) return 1
      if (bi === -1) return -1
      return ai - bi
    }),
  },
  {
    id: "framework",
    label: "Stack",
    options: [...new Set(TEMPLATES.map((t) => t.framework).filter(Boolean) as string[])].sort(),
  },
  {
    id: "category",
    label: "Category",
    options: [...new Set(TEMPLATES.map((t) => t.category))].sort(),
  },
  {
    id: "track",
    label: "Track",
    options: [...new Set(TEMPLATES.map((t) => t.track).filter(Boolean) as TemplateTrack[])].sort(),
  },
  {
    id: "sourceKind",
    label: "Source",
    options: ["git", "docker"],
  },
]

// ─── Gradient map for cards ──────────────────────────────────────────────────

export const GRADIENT_MAP: Record<string, string> = {
  "Next.js": "from-slate-900 via-slate-800 to-slate-900",
  "Express": "from-amber-950 via-orange-950 to-slate-900",
  "Astro": "from-purple-950 via-indigo-950 to-slate-900",
  "Svelte": "from-orange-950 via-red-950 to-slate-900",
  "Nuxt": "from-emerald-950 via-green-950 to-slate-900",
  "FastAPI": "from-emerald-950 via-teal-950 to-slate-900",
  "Hono": "from-rose-950 via-red-950 to-slate-900",
  "Vue": "from-emerald-950 via-teal-950 to-slate-900",
  "Remix": "from-indigo-950 via-violet-950 to-slate-900",
  "Django": "from-green-950 via-emerald-950 to-slate-900",
  "Flask": "from-gray-900 via-slate-800 to-gray-900",
  "NestJS": "from-red-950 via-rose-950 to-slate-900",
  "Go": "from-cyan-950 via-sky-950 to-slate-900",
  "Deno": "from-slate-900 via-gray-800 to-slate-900",
  "SolidJS": "from-blue-950 via-indigo-950 to-slate-900",
  "Vite": "from-violet-950 via-purple-950 to-slate-900",
  "Preact": "from-purple-950 via-violet-950 to-slate-900",
  "Qwik": "from-blue-950 via-cyan-950 to-slate-900",
  "Eleventy": "from-gray-900 via-slate-800 to-gray-900",
  "Lit": "from-blue-950 via-sky-950 to-slate-900",
  "Node.js": "from-green-950 via-lime-950 to-slate-900",
  "default": "from-slate-900 via-gray-800 to-slate-900",
}

const getIconComponent = (icon: string) => {
  switch (icon) {
    case "globe": return Globe
    case "server": return Server
    case "database": return Database
    case "code": return Code2
    case "boxes": return Boxes
    case "shield": return Shield
    default: return Server
  }
}
